services:
    db:
        image: postgres:alpine
        container_name: zapchat_d
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: vikas7490
            POSTGRES_PASSWORD: vikas12630
            POSTGRES_DB: zapchat_db
        volumes:
            - pgdata:/var/lib/postgresql

volumes:
    pgdata: